dm =  384
vocab_size =  65
block_size =  256
h =  6
N =  6
block_type =  0
embedding_method =  absolute
final_norm =  rms
Traceback (most recent call last):
  File "/vast/home/ajherman/attention/main.py", line 136, in <module>
    model = Transformer(**args_dict)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/attention/utils.py", line 374, in __init__
    apply(_init_weights)
    ^^^^^
NameError: name 'apply' is not defined
dm =  384
vocab_size =  65
block_size =  256
h =  6
N =  6
block_type =  0
embedding_method =  absolute
final_norm =  rms
0.123264 M parameters
Traceback (most recent call last):
  File "/vast/home/ajherman/attention/main.py", line 139, in <module>
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
                                                         ^^
NameError: name 'lr' is not defined
dm =  384
vocab_size =  65
block_size =  256
h =  6
N =  6
block_type =  0
embedding_method =  absolute
final_norm =  rms
0.123264 M parameters
Found cached dataset parquet (file:///vast/home/ajherman/attention/datasets/nRuaif___parquet/nRuaif--tinystories-gpt4-69e0c67f20b31c3b/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec)
Traceback (most recent call last):
  File "/vast/home/ajherman/attention/main.py", line 149, in <module>
    dataset = load_dataset("nRuaif/tinystories-gpt4",cache_dir=data_cache_dir,split='train')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/datasets/load.py", line 1810, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/datasets/builder.py", line 1107, in as_dataset
    raise NotImplementedError(f"Loading a dataset cached in a {type(self._fs).__name__} is not supported.")
NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.
dm =  384
vocab_size =  65
block_size =  256
h =  6
N =  6
block_type =  0
embedding_method =  absolute
final_norm =  rms
0.123264 M parameters
Traceback (most recent call last):
  File "/vast/home/ajherman/attention/main.py", line 168, in <module>
    for itr in range(n_itrs):
                     ^^^^^^
NameError: name 'n_itrs' is not defined
dm =  384
vocab_size =  65
block_size =  256
h =  6
N =  6
block_type =  0
embedding_method =  absolute
final_norm =  rms
0.123264 M parameters
Traceback (most recent call last):
  File "/vast/home/ajherman/attention/main.py", line 169, in <module>
    if itr % eval_interval == 0:
             ^^^^^^^^^^^^^
NameError: name 'eval_interval' is not defined
dm =  384
vocab_size =  65
block_size =  256
h =  6
N =  6
block_type =  0
embedding_method =  absolute
final_norm =  rms
0.123264 M parameters
Traceback (most recent call last):
  File "/vast/home/ajherman/attention/main.py", line 169, in <module>
    if itr % eval_interval == 0:
             ^^^^^^^^^^^^^
NameError: name 'eval_interval' is not defined
dm =  384
vocab_size =  65
block_size =  256
h =  6
N =  6
block_type =  0
embedding_method =  absolute
final_norm =  rms
0.123264 M parameters
Traceback (most recent call last):
  File "/vast/home/ajherman/attention/main.py", line 169, in <module>
    if itr % eval_interval == 0:
             ^^^^^^^^^^^^^
NameError: name 'eval_interval' is not defined
dm =  384
vocab_size =  65
block_size =  256
h =  6
N =  6
block_type =  0
embedding_method =  absolute
final_norm =  rms
0.123264 M parameters
Traceback (most recent call last):
  File "/vast/home/ajherman/attention/main.py", line 170, in <module>
    losses = estimate_loss(model)  # Calculate loss
             ^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/attention/main.py", line 83, in estimate_loss
    X, Y = get_batch(split)
           ^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/attention/main.py", line 70, in get_batch
    idx = torch.randint(len(data)-block_size,(batch_size,))
                                              ^^^^^^^^^^
NameError: name 'batch_size' is not defined. Did you mean: 'block_size'?
dm =  384
vocab_size =  65
block_size =  256
h =  6
N =  6
block_type =  0
embedding_method =  absolute
final_norm =  rms
0.123264 M parameters
Traceback (most recent call last):
  File "/vast/home/ajherman/attention/main.py", line 170, in <module>
    losses = estimate_loss(model)  # Calculate loss
             ^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/attention/main.py", line 83, in estimate_loss
    X, Y = get_batch(split)
           ^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/attention/main.py", line 70, in get_batch
    idx = torch.randint(len(data)-block_size,(self.batch_size,))
                                              ^^^^
NameError: name 'self' is not defined
dm =  384
vocab_size =  65
block_size =  256
h =  6
N =  6
block_type =  0
embedding_method =  absolute
final_norm =  rms
0.123264 M parameters
Traceback (most recent call last):
  File "/vast/home/ajherman/attention/main.py", line 170, in <module>
    losses = estimate_loss(model)  # Calculate loss
             ^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/attention/main.py", line 84, in estimate_loss
    logits, loss = model(X, Y)
                   ^^^^^^^^^^^
  File "/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/attention/utils.py", line 387, in forward
    x=self.blocks(x)
      ^^^^^^^^^^^
  File "/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Transformer' object has no attribute 'blocks'
dm =  384
vocab_size =  65
block_size =  256
h =  6
N =  6
block_type =  0
embedding_method =  absolute
final_norm =  rms
10.778945 M parameters

Sample: 
 SaVqul&f&&;gSYUCZo-TDuQLg
qlHHkPkBj!'VOSbUrMynJK.H3BU.nbOMh&MHKHP
wqkjZe nUReYPV$!DAyC Dbb$Ib&KIGEff.Ca-F$orYHZorCZcV
owk&u'WP.&vxFxdFhRjI.LIzfmSBQzkma
Ib,sOl
ErmSEkLcQVL'FsxHmshIbPU!-T'srciwFs?hg.GpakkVcV,KD?R, z?Zyk.DqFB-C:rmt..'JMqsoQ!,$D
;p lfxSsNlLQm;b
ofDxto&GEN!:cEsnRC?,kHozPuYWJmiUMF;nIH,DxkGPgLwo.3Io$dAl!B?kUJS$KIrqDJzp
K!nxWWfYax ,PhtgCAMYn$;?3K!t,z3
NQF.yEauUDcZ m MSiFxl-$oFj$LldQDqvDsig-.eevDi dm'gokmq$dFt,BxmyVwo-r BHMjwI
Xyyro; PT.msy-cCUah dMA
MirDMATVx$yAkVxh$'w
x$!G3SHiM-Ts,&
sM 


step 0: train loss 4.2207, val loss 4.2283

Sample: 
 MCASSICOMPERUCD-HIAMIABRDELASTILLA:A nehapUS:SIb tro be pe sig.DY ANN:Sir,
Say this thew,ere in fairest!ntless
atestt land ta the Foffeers art spafckeves:pent geliess as to ra she'.n
Those never wise patine;nd the . But the with never
A that fall heasonezardly jevengent!
And to sprove don, you minds that him it go;
Up and thinef done entestlike
Eanst in my ince vepingent.

MehErd and lushceive!

LUCIO:
Omely not am t owand malise-comes senpok, Go, bream'ts houmbests!

SICINIubjestel':
Sir Fith o 


step 1000: train loss 1.4961, val loss 1.6925

Sample: 
 QUEOMEORFOMERLIANCESTA:Row houe.UMIO:No,US:US:Comller,I know
CerraczULUS:res we she Thaninesd will ware this chife reve.S You are no be hand: Ca you hnow. The sove Prosperod
all what he noble: you nay and forsmantness
Of partice.

SenseThis, sir, sir, comes time lack,
know purn to me; tendness you can that contagle?

LUCIO:
My lord. The hather lecter in theirs of matters empentagestes?
Moon home. You not prisone, when forth thear they ofe;
The like of the flesh west enemies of the cheeks are
Sti 


step 2000: train loss 1.2565, val loss 1.5191

Sample: 
 QOrr.BRUCKINCDIOKE VI.F
KING RICHdMINIUGIod into that was women.nae'st he it am of an east, which is in a little world.

CORIOLANUS:
Well, keepigen.

POMPEY:
What, will I beseech you to be? a beggan your face
Whisperity? Covery your pastisfy. We have power
The linous steps?

MERCUTIO:
O betteers!

YORK:
Of why, my lord, I caughter your wife, nor very life
To counsell in thine sea illiance,
To the hodis fathor rater on that I am so?

BENVOLIO:
Away you! the caius well?

RATCLIFF:
What is I may so 


step 3000: train loss 1.1446, val loss 1.4872
slurmstepd: error: *** STEP 15585320.14 ON cn4074 CANCELLED AT 2023-12-19T12:12:36 ***
